name: Validate Remote (Nightly)
on:
  schedule: [{ cron: '23 2 * * *' }]
  workflow_dispatch:
jobs:
  nightly:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Sanity check (kit exists)
        run: |
          test -f ai-manifest-kit/scripts/validate-ai.mjs || (echo "kit missing: vendor ai-manifest-kit into repo" && exit 1)

      - name: Install deps (retry)
        run: |
          for i in 1 2 3; do npm i ajv ajv-formats node-fetch@^3 https-proxy-agent socks-proxy-agent && break || (echo "npm install retry $i" && sleep 3); done

      - name: Validate remote
        run: |
          node ai-manifest-kit/scripts/validate-ai.mjs   --url https://ai-manifest.org/.well-known/ai.json   --check-remote --strict 1 --out _reports/ai_remote.json
          node ai-manifest-kit/scripts/validate-jwks.mjs --url https://ai-manifest.org/.well-known/jwks.json --out _reports/jwks_remote.json
          node ai-manifest-kit/scripts/validate-crl.mjs  --url https://ai-manifest.org/.well-known/ai-crl.json --out _reports/crl_remote.json

      - uses: actions/upload-artifact@v4
        with:
          name: nightly-remote-reports
          path: _reports/*.json
