name: Validate Remote (Nightly)
on:
schedule: [{ cron: '23 2 * * *' }]
workflow_dispatch:
jobs:
nightly:
runs-on: ubuntu-latest
steps:
uses: actions/checkout@v4
uses: actions/setup-node@v4
with: { node-version: '20' }
run: npm i ajv ajv-formats node-fetch@^3 https-proxy-agent socks-proxy-agent
name: Validate remote
run: |
node ai-manifest-kit/scripts/validate-ai.mjs --url https://ai-manifest.org/.well-known/ai.json --check-remote --strict 1 --out _reports/ai_remote.json
node ai-manifest-kit/scripts/validate-jwks.mjs --url https://ai-manifest.org/.well-known/jwks.json --out _reports/jwks_remote.json
node ai-manifest-kit/scripts/validate-crl.mjs --url https://ai-manifest.org/.well-known/ai-crl.json --out _reports/crl_remote.json
uses: actions/upload-artifact@v4
with: { name: nightly-remote-reports, path: _reports/*.json }
